OpenGLProc(GenBuffers, GENBUFFERS)
OpenGLProc(BindBuffer, BINDBUFFER)
OpenGLProc(BufferData, BUFFERDATA)
OpenGLProc(CreateShader, CREATESHADER)
OpenGLProc(ShaderSource, SHADERSOURCE)
OpenGLProc(CompileShader, COMPILESHADER)
OpenGLProc(GetShaderiv, GETSHADERIV)
OpenGLProc(GetShaderInfoLog, GETSHADERINFOLOG)
OpenGLProc(CreateProgram, CREATEPROGRAM)
OpenGLProc(AttachShader, ATTACHSHADER)
OpenGLProc(LinkProgram, LINKPROGRAM)
OpenGLProc(GetProgramiv, GETPROGRAMIV)
OpenGLProc(GetProgramInfoLog, GETPROGRAMINFOLOG)
OpenGLProc(UseProgram, USEPROGRAM)
OpenGLProc(DeleteShader, DELETESHADER)
OpenGLProc(VertexAttribPointer, VERTEXATTRIBPOINTER)
OpenGLProc(EnableVertexAttribArray, ENABLEVERTEXATTRIBARRAY)
OpenGLProc(GenVertexArrays, GENVERTEXARRAYS)
OpenGLProc(BindVertexArray, BINDVERTEXARRAY)
OpenGLProc(GetUniformLocation, GETUNIFORMLOCATION)
OpenGLProc(GenerateMipmap, GENERATEMIPMAP)

//get uniform overloads
OpenGLProc(Uniform4f, UNIFORM4F)
OpenGLProc(Uniform3f, UNIFORM3F)
OpenGLProc(Uniform1f, UNIFORM1F)
#undef OpenGLProc
